spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_management?useSSL=false&serverTimezone=UTC
    username: admin
    password: SNCorridor147@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # For development, 'update' is convenient. For prod, 'validate' or Flyway/Liquibase is better.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect # For MySQL 8+

  redis:
    host: localhost
    port: 6379

logging:
  level:
    com.community.management: DEBUG
    org.springframework.security: DEBUG

app:
  jwt:
    secret: "ThisIsASecretKeyForJWTGenerationAndValidationWhichIsLongEnoughForHS512" # Replace with a secure key in production
    expiration: 86400000 # 24 hours

file:
  upload-dir: "./uploads"